language: python

python:
  - "3.5"

sudo: false
cache: pip

git:
  depth: 5
  quiet: true

addons:
  apt:
    packages:
    - expect-dev  # provides unbuffer utility
    - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0"
  - WKHTMLTOPDF_VERSION="0.12.4"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success